version: '3.8'

networks:
  app_net:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8009:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=site_db
      - POSTGRES_PASSWORD=site_db
      - POSTGRES_DB=site_db
    networks:
      - app_net

volumes:
  postgres_data:
