# Generated by Django 4.2.5 on 2023-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(max_length=255),
        ),
    ]
